### ISSUE TITLE
Add an option to ignore assertions on unstable rust toolchain

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/expect-test#13]
Hi, sorry for disappearing for a long time, I've been being really busy with the commercial project and other life stuff...

Well, anyway thanks for this awesome library. We've been using it with success, but there still is space for improvements.
We are running our tests on `beta` and `nightly` versions of the compiler toolchain to detect possible regressions when upgrading to the new stable release.
Unfortunately, `std::fmt::Debug` representation does break from time to time and now we are seeing all our tests on `unstable` toolchains fail because of minor changes to some `std::fmt::Debug` impls of some types.

As a workaround, we are using [`rustversion`](https://docs.rs/rustversion) crate to disable tests that use `expect-test` on unstable toolchain versions.
That requires us remembering to add it to dependencies whenever we use `expect-test` and also add this proc macro attribute to all test functions that use `expect-test`.

I wonder if you have any other solution to this problem, maybe `expect-test` could expose a cargo feature that will make it depend on `rustversion` and skip assertions on `unstable` toolchain to simplify our life?

Otherwise I think we will just drop jobs that use unstable toolchains...

**Comment by matklad** [comment]
Note: I advise using autocfg rather than rustcversion.

The solution I’d do is just not running the tests on nightly: iirc, I do similar thing for once-cell, where the level of support for non-stable compilers is “passes cargo-check”.

if you do want to test on nightly, I’d advice to define your own top-level assert_debug_eq function which is *independent* of rustc version, and does normalization. For example, if debug change is the addition of trailing comma, then .replace(‘“‘, “”) is such normalization. If this is a change in char escapes, then replacing \c with c would work, etc.

Overall, assert_debug_eq is a convenience function to get something working with as little work as possible. It’s generally preferable to define your own string serialization, and use assert_eq.

just to add one more option, you can also serialize things to json instead of using debug.

**Comment by Veetaha** [comment]
I think you convinced me that actually running the test on unstable toolchains is not that useful. Guess we'll downgrade to `pass cargo-check` level of feedback from them because anyway it's not worth the pain.

But the idea of sanitizing the snapshots didn't come to my mind, thanks!
I'll close this issue since I guess it's not what this library can really help with...
